[workspace]
resolver = "2"
members = [
    "cache",
    "diff",
    "examples/showcase",
    "executor",
    "font",
    "kernel",
    "layout",
    "platform/desktop",
    "platform/terminal",
    "render/cpu",
    "render/term",
]

[workspace.package]
license = "MIT"

[workspace.dependencies]
blit = { path = "kernel" }
blit-diff = { path = "diff" }
blit-executor = { path = "executor" }
blit-font = { path = "font" }
blit-layout = { path = "layout" }
blit-showcase = { path = "examples/showcase" }
