[package]
name = "blit-site"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
blit.workspace = true
blit-web.workspace = true

[build-dependencies]
serde = { version = "1", features = ["derive"] }
toml = { version = "0.9", default-features = false, features = ["parse", "serde"] }
