[package]
name = "blit-tui-render"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
base64 = "0.22"
blit.workspace = true
blit_cache = { path = "../../cache" }
unicode-segmentation = "1.12"
unicode-width = "0.2"

[dev-dependencies]
divan = "0.1"

[[bench]]
name = "tui"
harness = false
