[package]
name = "blit-term"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
base64 = "0.22"
blit.workspace = true
unicode-segmentation = "1.12"
unicode-width = "0.2"

[dev-dependencies]
blit-showcase.workspace = true
divan = "0.1"

[[bench]]
name = "terminal"
harness = false
